#define yy_create_buffer yyrel_create_buffer
#define yy_delete_buffer yyrel_delete_buffer
#define yy_scan_buffer yyrel_scan_buffer
#define yy_scan_string yyrel_scan_string
#define yy_scan_bytes yyrel_scan_bytes
#define yy_flex_debug yyrel_flex_debug
#define yy_init_buffer yyrel_init_buffer
#define yy_flush_buffer yyrel_flush_buffer
#define yy_load_buffer_state yyrel_load_buffer_state
#define yy_switch_to_buffer yyrel_switch_to_buffer
#define yyin yyrelin
#define yyleng yyrelleng
#define yylex yyrellex
#define yyout yyrelout
#define yyrestart yyrelrestart
#define yytext yyreltext
#define yywrap yyrelwrap

#line 20 "Rellexer.C"
/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /share/apps/icme/depository/FEM.d/Structopt.d/Rellexer.C,v 1.2 2007/09/05 00:37:47 pavery Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <cstdio>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <cstdlib>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <cstdlib>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 222
#define YY_END_OF_BUFFER 223
static yyconst short int yy_accept[639] =
    {   0,
        0,    0,  223,  222,  212,  209,  210,  211,  211,  222,
      213,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      212,    0,  213,  215,  214,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,   36,   37,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  124,  125,  126,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  214,    0,    0,    0,
      220,    0,  217,    0,   12,   13,    0,    0,   17,    0,
      158,    0,   20,   21,  160,    0,  159,   25,   26,   27,
      192,    0,   29,    0,   31,   34,    0,    0,    0,    0,
        0,  208,   44,   45,    0,    0,    0,    0,   50,   51,
       69,   52,    0,    0,   60,    0,    0,    0,   64,   65,
        0,    0,    0,   94,   95,  165,   68,   96,    0,   97,
       98,    0,    0,  108,  118,  110,  119,    0,  109,    6,

        0,    0,    0,    0,  177,  178,  179,  180,  181,  182,
      127,    0,    0,    0,  141,  142,  156,    0,    0,  176,
      183,  184,  185,  186,  187,  188,  189,  190,  191,    0,
        0,    0,  198,    0,    0,    0,    0,  200,  201,  202,
      203,  204,    0,  206,  207,    0,  221,    0,  218,    0,
      219,    0,  216,    0,   12,   13,   14,    0,   17,   18,
      158,   19,   20,   21,  160,   23,   24,    0,  159,   26,
      193,  194,    0,   29,    0,   31,   34,   32,   33,   47,
        0,   40,   39,   38,   41,    0,   44,   45,    0,    0,
       49,    0,   50,    9,   51,   52,   53,    0,    0,    0,

        0,    0,    0,   60,    0,   61,   63,   64,    0,    0,
        0,   94,   95,  165,    0,    0,    0,    0,    0,    0,
       96,    0,    0,    0,    0,    0,    0,    0,    0,  161,
        0,    0,  108,  118,    0,    0,    0,    0,    0,    0,
        0,  120,    0,    0,  166,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  156,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  196,    0,  198,    0,
      199,  167,    0,  205,  207,    0,   14,    0,   23,   24,
        0,   28,    0,   32,   33,   47,    0,   40,   39,   38,

       41,   42,   43,   46,   48,   49,   49,  162,   53,    0,
        0,    0,    0,    0,    0,    0,   63,   66,   67,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        0,    0,  106,  161,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  120,    0,    0,  166,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      139,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   22,    0,  197,  167,    0,  205,

       11,    0,    0,    0,   28,    0,  163,   46,   48,   49,
      162,   57,   58,   55,   56,   59,   54,    0,    0,   78,
       80,   75,   91,   90,   93,   92,   70,   71,   74,   73,
       77,   87,   85,   88,   86,   79,   89,   81,   82,   83,
       84,   76,   72,    7,  104,  100,  102,   99,  103,  101,
      105,  107,    2,  113,  117,  111,  112,  114,  116,  115,
      121,  122,  123,    1,  132,  136,  128,  130,  129,  135,
      133,  134,  131,  138,  137,    0,  140,  153,  147,  155,
      146,  152,  151,  144,  145,  143,  148,  154,  149,  150,
      168,  170,  169,  172,   10,  171,  157,  173,  175,  174,

       22,    0,  197,    0,    0,    0,  195,   30,  163,    5,
       57,   58,   55,   56,   59,   62,    0,  121,  122,  123,
        8,  168,  170,  169,  172,  171,  175,  174,    0,    3,
       16,   15,    5,    0,  164,    4,  164,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    5,
        6,    7,    8,    9,   10,   11,    1,   12,   13,   14,
       12,   12,   12,   12,   12,   12,   12,   15,    1,    1,
       16,    1,    1,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,    1,   44,   45,   46,    1,   47,   47,   47,   48,

       49,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   50,    1,   51,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    1,    1,    1,    2,    2,    2,    1,
        1
    } ;

static yyconst short int yy_base[727] =
    {   0,
        0,    0,  759,  760,  756,  760,  760,  760,   41,   44,
       48,   80,   42,   49,   51,   54,   73,   74,   40,   89,
       96,   91,  105,  105,  109,  139,  144,  727,  114,   76,
      754,  134,    0,  170,  173,  187,  194,  720,  735,  727,
      718,  734,  733,  728,  712,  711,  725,  715,  131,  119,
       43,  715,  166,  106,  760,  760,  760,  713,  117,  711,
      151,  713,  137,  715,  702,  704,  704,  707,  705,  703,
      713,  699,  184,  701,  708,  688,  711,  704,   48,  686,
      708,  181,  696,  691,  169,  693,  695,  691,  685,  684,
      692,  699,  687,  686,  693,  692,  760,  760,  760,  186,

      188,  184,  680,  674,  679,  676,  679,  158,  677,  198,
      200,  202,  674,  675,  211,  674,  685,  676,  666,  671,
      205,  670,  658,  665,  236,  243,  246,  260,  267,  249,
      270,  273,  276,  657,    0,    0,  663,  665,    0,  675,
        0,  660,    0,    0,    0,  261,    0,  760,    0,  760,
      227,  662,    0,  643,    0,    0,  126,  667,  274,  658,
      666,  760,    0,    0,  668,  655,  655,  657,  652,    0,
      760,    0,  660,  281,    0,  645,  642,  655,    0,  760,
      655,  640,  644,    0,    0,    0,  292,    0,  637,  760,
      301,  303,  643,    0,    0,  313,  760,  216,  760,  760,

      643,  645,  631,  630,  760,  760,  760,  760,  760,  760,
      332,  635,  635,  644,  760,  351,    0,  354,  226,  760,
      760,  760,  760,  760,  760,  760,  760,  760,  760,  634,
      631,  628,    0,  630,  639,  639,  636,  760,  760,  760,
      760,  760,  621,  760,    0,  288,  330,  339,  349,  373,
      381,  384,  387,  639,    0,    0,    0,  614,    0,  760,
        0,  760,    0,    0,    0,    0,    0,  633,    0,    0,
      760,  760,  634,    0,  621,    0,    0,    0,    0,    0,
      615,    0,    0,    0,    0,  279,    0,    0,  614,  627,
      611,  627,    0,    0,    0,    0,    0,  628,  620,  608,

      622,  613,  600,    0,  604,  760,    0,    0,  605,  617,
      606,    0,    0,    0,  327,  608,  595,  594,  599,  385,
        0,  611,  612,   84,  594,  609,  594,  608,  598,    0,
      594,  607,    0,    0,  604,  591,  585,  595,  588,  283,
      587,    0,  592,  586,    0,  598,  595,  591,  593,  575,
      593,  384,  591,  589,  579,  577,  576,  388,  563,  247,
      233,  578,  566,  567,  571,    0,  569,  287,  570,  567,
      562,  578,  559,  572,  561,  571,  760,  561,    0,  550,
      760,    0,  557,    0,    0,  553,    0,  304,    0,    0,
      567,    0,  553,    0,    0,    0,  548,    0,    0,    0,

        0,  760,  760,    0,    0,    0,  549,    0,    0,  547,
      553,  556,  551,  553,  545,  551,    0,  760,  760,  541,
      555,  544,  538,  285,  319,  387,  535,  341,  344,  398,
      410,  538,  551,  538,    0,  548,  538,  529,  530,  535,
      532,  543,  760,    0,  525,  531,  539,  523,  522,  520,
      515,  517,  520,  517,    0,  520,  529,    0,  514,  361,
      524,  518,  511,  515,  513,  523,  505,  509,  511,  517,
      760,  505,  517,  503,  508,  514,  505,  493,  381,  496,
      499,  500,  491,  488,  508,  495,  493,  484,  501,  503,
      485,  483,  479,  488,    0,  498,    0,    0,  480,    0,

      760,  488,  487,  475,    0,  476,    0,    0,    0,  488,
        0,    0,    0,    0,    0,    0,  760,  491,  478,  760,
      760,  760,  760,  760,  760,  760,  760,  760,  760,  760,
      760,  760,  760,  760,  760,  760,  760,  760,  760,  760,
      760,  760,  760,    0,  760,  760,  760,  760,  760,  760,
      760,  760,  760,  760,  760,  760,  760,  760,  760,  760,
        0,    0,    0,  760,  760,  760,  760,  760,  760,  760,
      760,  760,  760,  760,  760,  471,  760,  760,  760,  760,
      760,  760,  760,  760,  760,  760,  760,  760,  760,  760,
        0,    0,    0,    0,  760,    0,  760,  760,    0,    0,

        0,  469,    0,  475,  468,  483,  760,  760,    0,    0,
        0,    0,    0,    0,    0,  760,  484,    0,    0,    0,
      760,    0,    0,    0,    0,    0,    0,    0,  464,  760,
      760,  760,    0,  471,    0,  760,    0,  760,  496,  495,
      494,  493,  492,  491,  490,  489,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  477,  476,  475,
      474,  473,  472,  471,  470,  469,  468,  467,  466,  465,
      464,  463,  462,  461,  460,  459,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,

      434,  433,  432,  431,  430,  429,  428,  423,  412,  411,
      408,  389,  375,  363,  356,  335,  332,  329,  303,  276,
      269,  222,  196,  113,  110,   85
    } ;

static yyconst short int yy_def[727] =
    {   0,
      638,    1,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,   11,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,

      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  639,  640,  638,  638,  641,  638,
      642,  638,  643,  644,  645,  638,  646,  638,  647,  638,
      638,  638,  648,  638,  649,  650,  638,  638,  638,  638,
      638,  638,  651,  652,  638,  638,  638,  638,  653,  654,
      638,  655,  638,  638,  656,  638,  638,  638,  657,  638,
      638,  638,  638,  658,  659,  660,  638,  661,  638,  638,
      638,  638,  638,  662,  663,  638,  638,  638,  638,  638,

      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  664,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  665,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  666,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  639,  640,  667,  638,  641,  638,
      642,  638,  643,  644,  645,  668,  669,  638,  646,  647,
      638,  638,  638,  648,  638,  649,  650,  670,  671,  672,
      638,  673,  674,  675,  676,  638,  677,  678,  638,  638,
      679,  638,  680,  680,  681,  682,  683,  638,  638,  638,

      638,  638,  638,  684,  638,  638,  685,  686,  638,  638,
      638,  687,  688,  689,  638,  638,  638,  638,  638,  638,
      690,  638,  638,  638,  638,  638,  638,  638,  638,  691,
      638,  638,  692,  693,  638,  638,  638,  638,  638,  638,
      638,  694,  638,  638,  695,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  696,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  697,  638,
      638,  698,  638,  699,  700,  638,  701,  638,  668,  669,
      638,  702,  638,  670,  671,  672,  638,  673,  674,  675,

      676,  638,  638,  703,  704,  679,  679,  705,  683,  638,
      638,  638,  638,  638,  638,  638,  685,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  706,  638,  638,  638,  638,  638,
      638,  638,  638,  691,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  694,  638,  638,  695,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  707,  638,  708,  698,  638,  699,

      638,  638,  638,  638,  702,  638,  709,  703,  704,  679,
      705,  710,  711,  712,  713,  714,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  706,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      715,  716,  717,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      718,  719,  720,  721,  638,  722,  638,  638,  723,  724,

      707,  638,  708,  638,  638,  638,  638,  638,  709,  725,
      710,  711,  712,  713,  714,  638,  638,  715,  716,  717,
      638,  718,  719,  720,  721,  722,  723,  724,  638,  638,
      638,  638,  725,  638,  726,  638,  726,    0,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,

      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638
    } ;

static yyconst short int yy_nxt[812] =
    {   0,
        4,    5,    6,    7,    8,    8,    8,    9,    8,    9,
       10,   11,   11,   11,    8,    8,   12,    4,   13,   14,
       15,   16,   17,    4,   18,    4,   19,   20,   21,   22,
       23,   24,    4,   25,   26,   27,   28,   29,    4,    4,
       30,    4,    8,    8,    8,    4,    4,    4,    4,    8,
        8,   32,   33,   33,   33,   34,   34,   34,   35,   33,
       33,   33,   48,  151,   74,   52,  184,   36,   37,   53,
       64,   58,   49,   54,   75,   50,  152,   51,   59,   60,
       61,   65,  185,   62,   66,   63,  637,   67,   55,   56,
       57,   68,  123,   69,   72,   36,   37,   38,   39,   40,

       41,   70,  437,   73,  124,   76,   71,   77,  438,   42,
       43,  633,   79,   44,  628,   45,   46,   47,   84,   78,
       80,   85,   87,   88,   81,   90,   82,   86,   91,   94,
      119,   95,   83,   92,  120,  159,   89,  160,   96,  156,
      157,   93,  121,  149,  122,   34,   34,   34,   97,   98,
       99,  100,  101,  278,  150,  102,  103,  279,  104,  145,
      146,  147,  113,  105,  114,  148,  106,  115,  116,  107,
      162,  163,  165,  166,  108,  109,  218,  117,  110,  111,
      112,   34,   34,   34,  127,  127,  127,  154,  192,  125,
      126,  219,  128,  129,  130,  155,  130,  627,  131,  131,

      131,  132,  193,  132,  176,  133,  133,  133,  177,  188,
      189,  211,  212,  205,  206,  208,  209,  125,  126,  178,
      128,  129,  207,  626,  210,  221,  222,  224,  225,  227,
      228,  232,  240,  241,  223,  233,  226,  341,  229,  271,
      272,  242,  234,  246,  342,  246,  373,  247,  247,  247,
      248,  479,  248,  374,  249,  249,  249,  127,  127,  127,
      131,  131,  131,  375,  477,  128,  129,  250,  480,  250,
      625,  251,  251,  251,  252,  478,  252,  624,  253,  253,
      253,  131,  131,  131,  133,  133,  133,  133,  133,  133,
      281,  402,  403,  128,  129,  266,  267,  298,  268,  247,

      247,  247,  299,  486,  623,  282,  452,  283,  315,  300,
      316,  284,  523,  317,  301,  302,  303,  323,  453,  329,
      318,  524,  324,  319,  330,  325,  320,  487,  326,  335,
      622,  336,  327,  620,  331,  328,  619,  337,  502,  503,
      338,  247,  247,  247,  339,  421,  525,  340,  347,  348,
      249,  249,  249,  349,  422,  526,  350,  618,  423,  351,
      249,  249,  249,  352,  615,  353,  354,  358,  532,  359,
      367,  534,  360,  368,  369,  361,  614,  533,  362,  565,
      535,  363,  364,  365,  251,  251,  251,  370,  566,  371,
      613,  372,  251,  251,  251,  253,  253,  253,  253,  253,

      253,  428,  429,  430,  465,  466,  473,  474,  527,  612,
      584,  528,  611,  609,  529,  536,  475,  467,  585,  431,
      432,  433,  434,  530,  603,  537,  538,  539,  540,  601,
      544,  511,  509,  508,  505,  387,  385,  500,  498,  379,
      366,  458,  455,  334,  333,  444,  321,  314,  313,  312,
      308,  417,  304,  409,  296,  295,  293,  406,  288,  287,
      401,  400,  399,  398,  396,  395,  394,  390,  389,  387,
      385,  379,  366,  334,  333,  321,  314,  313,  312,  308,
      304,  296,  295,  293,  288,  287,  277,  276,  274,  270,
      269,  265,  264,  263,  261,  259,  256,  255,  636,  635,

      634,  632,  631,  630,  629,  621,  617,  616,  610,  608,
      607,  606,  605,  604,  602,  600,  599,  598,  597,  596,
      595,  594,  593,  592,  591,  590,  589,  588,  587,  586,
      583,  582,  581,  580,  579,  578,  577,  576,  575,  574,
      573,  572,  571,  570,  569,  568,  567,  564,  563,  562,
      561,  560,  559,  558,  557,  556,  555,  554,  553,  552,
      551,  550,  549,  548,  547,  546,  545,  543,  542,  541,
      531,  522,  521,  520,  519,  518,  517,  516,  515,  514,
      513,  512,  510,  507,  506,  504,  501,  499,  497,  496,
      495,  494,  493,  492,  491,  490,  489,  488,  485,  484,

      483,  482,  481,  476,  472,  471,  470,  469,  468,  464,
      463,  462,  461,  460,  459,  457,  456,  454,  451,  450,
      449,  448,  447,  446,  445,  443,  442,  441,  440,  439,
      436,  435,  427,  426,  425,  424,  420,  419,  418,  416,
      415,  414,  413,  412,  411,  410,  408,  407,  405,  404,
      397,  393,  392,  391,  388,  386,  384,  383,  382,  381,
      380,  378,  377,  376,  357,  356,  355,  346,  345,  344,
      343,  332,  322,  311,  310,  309,  307,  306,  305,  297,
      294,  292,  291,  290,  289,  286,  285,  280,  275,  273,
      262,  260,  258,  257,  254,  245,  244,  243,  239,  238,

      237,  236,  235,  231,  230,  220,  217,  216,  215,  214,
      213,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  191,  190,  187,  186,  183,  182,  181,  180,
      179,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      164,  161,  158,  153,  144,  143,  142,  141,  140,  139,
      138,  137,  136,  135,  134,   31,  118,   31,  638,    3,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,

      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638
    } ;

static yyconst short int yy_chk[812] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    9,    9,    9,   10,   10,   10,   11,   11,
       11,   11,   13,   51,   19,   14,   79,   11,   11,   14,
       16,   15,   13,   14,   19,   13,   51,   13,   15,   15,
       15,   16,   79,   15,   16,   15,  726,   16,   14,   14,
       14,   17,   30,   17,   18,   11,   11,   12,   12,   12,

       12,   17,  324,   18,   30,   20,   17,   20,  324,   12,
       12,  725,   21,   12,  724,   12,   12,   12,   22,   20,
       21,   22,   23,   23,   21,   24,   21,   22,   24,   25,
       29,   25,   21,   24,   29,   59,   23,   59,   25,   54,
       54,   24,   29,   50,   29,   32,   32,   32,   25,   25,
       25,   26,   26,  157,   50,   26,   26,  157,   26,   49,
       49,   49,   27,   26,   27,   49,   26,   27,   27,   26,
       61,   61,   63,   63,   26,   26,  108,   27,   26,   26,
       26,   34,   34,   34,   35,   35,   35,   53,   85,   34,
       34,  108,   35,   35,   36,   53,   36,  723,   36,   36,

       36,   37,   85,   37,   73,   37,   37,   37,   73,   82,
       82,  102,  102,  100,  100,  101,  101,   34,   34,   73,
       35,   35,  100,  722,  101,  110,  110,  111,  111,  112,
      112,  115,  121,  121,  110,  115,  111,  198,  112,  151,
      151,  121,  115,  125,  198,  125,  219,  125,  125,  125,
      126,  361,  126,  219,  126,  126,  126,  127,  127,  127,
      130,  130,  130,  219,  360,  127,  127,  128,  361,  128,
      721,  128,  128,  128,  129,  360,  129,  720,  129,  129,
      129,  131,  131,  131,  132,  132,  132,  133,  133,  133,
      159,  286,  286,  127,  127,  146,  146,  174,  146,  246,

      246,  246,  174,  368,  719,  159,  340,  159,  187,  174,
      187,  159,  424,  187,  174,  174,  174,  191,  340,  192,
      187,  424,  191,  187,  192,  191,  187,  368,  191,  196,
      718,  196,  191,  717,  192,  191,  716,  196,  388,  388,
      196,  247,  247,  247,  196,  315,  425,  196,  211,  211,
      248,  248,  248,  211,  315,  425,  211,  715,  315,  211,
      249,  249,  249,  211,  714,  211,  211,  216,  428,  216,
      218,  429,  216,  218,  218,  216,  713,  428,  216,  460,
      429,  216,  216,  216,  250,  250,  250,  218,  460,  218,
      712,  218,  251,  251,  251,  252,  252,  252,  253,  253,

      253,  320,  320,  320,  352,  352,  358,  358,  426,  711,
      479,  426,  710,  709,  426,  430,  358,  352,  479,  320,
      320,  320,  320,  426,  708,  430,  431,  431,  431,  707,
      706,  705,  704,  703,  702,  701,  700,  699,  698,  697,
      696,  695,  694,  693,  692,  691,  690,  689,  688,  687,
      686,  685,  684,  683,  682,  681,  680,  679,  678,  677,
      676,  675,  674,  673,  672,  671,  670,  669,  668,  667,
      666,  665,  664,  663,  662,  661,  660,  659,  658,  657,
      656,  655,  654,  653,  652,  651,  650,  649,  648,  647,
      646,  645,  644,  643,  642,  641,  640,  639,  634,  629,

      617,  606,  605,  604,  602,  576,  519,  518,  510,  506,
      504,  503,  502,  499,  496,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      478,  477,  476,  475,  474,  473,  472,  470,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  459,  457,  456,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      442,  441,  440,  439,  438,  437,  436,  434,  433,  432,
      427,  423,  422,  421,  420,  416,  415,  414,  413,  412,
      411,  410,  407,  397,  393,  391,  386,  383,  380,  378,
      376,  375,  374,  373,  372,  371,  370,  369,  367,  365,

      364,  363,  362,  359,  357,  356,  355,  354,  353,  351,
      350,  349,  348,  347,  346,  344,  343,  341,  339,  338,
      337,  336,  335,  332,  331,  329,  328,  327,  326,  325,
      323,  322,  319,  318,  317,  316,  311,  310,  309,  305,
      303,  302,  301,  300,  299,  298,  292,  291,  290,  289,
      281,  275,  273,  268,  258,  254,  243,  237,  236,  235,
      234,  232,  231,  230,  214,  213,  212,  204,  203,  202,
      201,  193,  189,  183,  182,  181,  178,  177,  176,  173,
      169,  168,  167,  166,  165,  161,  160,  158,  154,  152,
      142,  140,  138,  137,  134,  124,  123,  122,  120,  119,

      118,  117,  116,  114,  113,  109,  107,  106,  105,  104,
      103,   96,   95,   94,   93,   92,   91,   90,   89,   88,
       87,   86,   84,   83,   81,   80,   78,   77,   76,   75,
       74,   72,   71,   70,   69,   68,   67,   66,   65,   64,
       62,   60,   58,   52,   48,   47,   46,   45,   44,   43,
       42,   41,   40,   39,   38,   31,   28,    5,    3,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,

      638,  638,  638,  638,  638,  638,  638,  638,  638,  638,
      638
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Rellexer.l"
#define INITIAL 0
#line 2 "Rellexer.l"
#ifdef STRUCTOPT
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <iostream>
#include "Optinp.h"
#include "Relparser.h"
#include "Optvar.h"
int yyrelline_num = 1;
#line 812 "Rellexer.C"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <cstdlib>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 16 "Rellexer.l"


#line 966 "Rellexer.C"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 639 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 760 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 18 "Rellexer.l"
{ return RNDVAR; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "Rellexer.l"
{ yyrellval.ival = 0; return RNDTYPE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "Rellexer.l"
{ yyrellval.ival = 1; return RNDTYPE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "Rellexer.l"
{ yyrellval.ival = 2; return RNDTYPE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "Rellexer.l"
{ return FAILURE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "Rellexer.l"
{ return PMAFLAG; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "Rellexer.l"
{ return MONTEALG; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "Rellexer.l"
{ yyrellval.ival = 0; return MONTEFLT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 30 "Rellexer.l"
{ return FORMALG; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 32 "Rellexer.l"
{ return STCRND; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 37 "Rellexer.l"
{ return DSGVAR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "Rellexer.l"
{ return ACCELERATION; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "Rellexer.l"
{ return ADJOINT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 43 "Rellexer.l"
{ return AERO; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "Rellexer.l"
{ return ANALYTIC; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "Rellexer.l"
{ return ANALYSIS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "Rellexer.l"
{ return AOATTACK; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "Rellexer.l"
{ return AREA; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "Rellexer.l"
{ return AUTOMATIC; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "Rellexer.l"
{ return AVEFLAG; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 57 "Rellexer.l"
{ return CENTRAL; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "Rellexer.l"
{ return THERMCOND;   }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "Rellexer.l"
{ return CONSTRAINT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "Rellexer.l"
{ return CONTINUE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 65 "Rellexer.l"
{ return OPCOSINUS; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "Rellexer.l"
{ return CRITERIA; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "Rellexer.l"
{ return FUNCRIT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "Rellexer.l"
{ return CTRLCOST; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 73 "Rellexer.l"
{ return DAMPING; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "Rellexer.l"
{ return DEFOPR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 77 "Rellexer.l"
{ return DENSITY; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "Rellexer.l"
{ return DISPLEVEL; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "Rellexer.l"
{ return DISPLACMENT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 83 "Rellexer.l"
{ return DIRECT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 85 "Rellexer.l"
{ return DX; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 86 "Rellexer.l"
{ return DY; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 87 "Rellexer.l"
{ return DZ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "Rellexer.l"
{ return ELCVOLT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "Rellexer.l"
{ return ELCRHS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "Rellexer.l"
{ return ELCPOW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "Rellexer.l"
{ yyrellval.ival = 0; return NODELE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 95 "Rellexer.l"
{ return EMOD1; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 96 "Rellexer.l"
{ return EMOD2; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 98 "Rellexer.l"
{ return ENERGY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 100 "Rellexer.l"
{ return EQUALITY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 102 "Rellexer.l"
{ return ESTAT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 103 "Rellexer.l"
{ yyrellval.ival=2;return ESTATCRIT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "Rellexer.l"
{ yyrellval.ival=1;return ESTATCRIT; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "Rellexer.l"
{ return FAILPROB; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 108 "Rellexer.l"
{ return FORWARD; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 110 "Rellexer.l"
{ return FREQUENCY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 112 "Rellexer.l"
{ return GENERATE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 114 "Rellexer.l"
{ return GMOD; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "Rellexer.l"
{ return GRDTYP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "Rellexer.l"
{ return GRDMTH; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "Rellexer.l"
{ return GRDRELINC; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "Rellexer.l"
{ return GRDABSINC; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "Rellexer.l"
{ return GRDFILTER; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "Rellexer.l"
{ return GRDSMI; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "Rellexer.l"
{ return INEQUALITY; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 125 "Rellexer.l"
{ return INIT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 127 "Rellexer.l"
{ return INERTIA; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 129 "Rellexer.l"
{ return INTFORCE; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "Rellexer.l"
{ return KINETIC; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "Rellexer.l"
{ return OPKSFUNC; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 135 "Rellexer.l"
{ return LAYER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "Rellexer.l"
{ return LCASE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 139 "Rellexer.l"
{ return MMAALG; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 140 "Rellexer.l"
{ return GCMALG; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 141 "Rellexer.l"
{ yyrellval.ival = 0; return MMAINT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 142 "Rellexer.l"
{ yyrellval.ival = 1; return MMAINT; } 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 143 "Rellexer.l"
{ yyrellval.ival = 2; return MMAINT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 144 "Rellexer.l"
{ yyrellval.ival = 3; return MMAINT; } 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "Rellexer.l"
{ yyrellval.ival = 4; return MMAINT; } 
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "Rellexer.l"
{ yyrellval.ival = 5; return MMAINT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "Rellexer.l"
{ yyrellval.ival = 6; return MMAINT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "Rellexer.l"
{ yyrellval.ival = 7; return MMAINT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 149 "Rellexer.l"
{ yyrellval.ival = 0; return MMAFLT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 150 "Rellexer.l"
{ yyrellval.ival = 1; return MMAFLT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 151 "Rellexer.l"
{ yyrellval.ival = 2; return MMAFLT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 152 "Rellexer.l"
{ yyrellval.ival = 3; return MMAFLT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 153 "Rellexer.l"
{ yyrellval.ival = 4; return MMAFLT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 154 "Rellexer.l"
{ yyrellval.ival = 5; return MMAFLT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 155 "Rellexer.l"
{ yyrellval.ival = 6; return MMAFLT; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 156 "Rellexer.l"
{ yyrellval.ival = 7; return MMAFLT; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 157 "Rellexer.l"
{ yyrellval.ival = 8; return MMAFLT; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 158 "Rellexer.l"
{ yyrellval.ival = 9; return MMAFLT; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 159 "Rellexer.l"
{ yyrellval.ival =10; return MMAFLT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 160 "Rellexer.l"
{ yyrellval.ival =11; return MMAFLT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 161 "Rellexer.l"
{ yyrellval.ival =12; return MMAFLT; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 162 "Rellexer.l"
{ yyrellval.ival =13; return MMAFLT; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 163 "Rellexer.l"
{ yyrellval.ival =14; return MMAFLT; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 164 "Rellexer.l"
{ yyrellval.ival =15; return MMAFLT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 167 "Rellexer.l"
{ return XMACH; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 169 "Rellexer.l"
{ return MASS; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 171 "Rellexer.l"
{ return MOMAER; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 173 "Rellexer.l"
{ return OPMULTI; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 175 "Rellexer.l"
{ return NLPALG; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 176 "Rellexer.l"
{ yyrellval.ival = 0; return NLPINT; } 
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 177 "Rellexer.l"
{ yyrellval.ival = 1; return NLPINT; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 178 "Rellexer.l"
{ yyrellval.ival = 2; return NLPINT; } 
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 179 "Rellexer.l"
{ yyrellval.ival = 3; return NLPINT; } 
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 180 "Rellexer.l"
{ yyrellval.ival = 4; return NLPINT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 181 "Rellexer.l"
{ yyrellval.ival = 0; return NLPFLT; } 
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 182 "Rellexer.l"
{ yyrellval.ival = 1; return NLPFLT; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 184 "Rellexer.l"
{ yyrellval.ival =1; return NODELE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 186 "Rellexer.l"
{ return NODPOS; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 188 "Rellexer.l"
{ return NUMERIC; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 190 "Rellexer.l"
{ return PHI; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 192 "Rellexer.l"
{ return OCMALG; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 193 "Rellexer.l"
{ yyrellval.ival = 0; return OCMINT; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 194 "Rellexer.l"
{ yyrellval.ival = 1; return OCMINT; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 195 "Rellexer.l"
{ yyrellval.ival = 0; return OCMFLT; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 196 "Rellexer.l"
{ yyrellval.ival = 1; return OCMFLT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 197 "Rellexer.l"
{ yyrellval.ival = 2; return OCMFLT; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 198 "Rellexer.l"
{ yyrellval.ival = 3; return OCMFLT; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 199 "Rellexer.l"
{ yyrellval.ival = 4; return OCMFLT; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 201 "Rellexer.l"
{ return OBJECTIVE; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 203 "Rellexer.l"
{ return FUNOPR; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 205 "Rellexer.l"
{ return PERMTVY;   }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 207 "Rellexer.l"
{ return PMACRITERIA; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 209 "Rellexer.l"
{ return PULLIN; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 211 "Rellexer.l"
{ return RELINDEX; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 213 "Rellexer.l"
{ return RX; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 214 "Rellexer.l"
{ return RY; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 215 "Rellexer.l"
{ return RZ; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 217 "Rellexer.l"
{ return SALALG; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 218 "Rellexer.l"
{ yyrellval.ival = 0; return SALINT; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 219 "Rellexer.l"
{ yyrellval.ival = 1; return SALINT; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 220 "Rellexer.l"
{ yyrellval.ival = 2; return SALINT; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 221 "Rellexer.l"
{ yyrellval.ival = 3; return SALINT; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 222 "Rellexer.l"
{ yyrellval.ival = 0; return SALFLT; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 223 "Rellexer.l"
{ yyrellval.ival = 1; return SALFLT; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 224 "Rellexer.l"
{ yyrellval.ival = 2; return SALFLT; }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 225 "Rellexer.l"
{ yyrellval.ival = 3; return SALFLT; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 226 "Rellexer.l"
{ yyrellval.ival = 4; return SALFLT; }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 227 "Rellexer.l"
{ yyrellval.ival = 5; return SALFLT; }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 228 "Rellexer.l"
{ yyrellval.ival = 6; return SALFLT; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 230 "Rellexer.l"
{ return SBOOM; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 231 "Rellexer.l"
{ return SDTEMP; }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 233 "Rellexer.l"
{ return OPSINUS; }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 235 "Rellexer.l"
{ return SLPALG; }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 236 "Rellexer.l"
{ yyrellval.ival = 0; return SLPINT; }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 237 "Rellexer.l"
{ yyrellval.ival = 1; return SLPINT; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 238 "Rellexer.l"
{ yyrellval.ival = 2; return SLPINT; }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 239 "Rellexer.l"
{ yyrellval.ival = 3; return SLPINT; }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 240 "Rellexer.l"
{ yyrellval.ival = 4; return SLPINT; }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 241 "Rellexer.l"
{ yyrellval.ival = 5; return SLPINT; }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 242 "Rellexer.l"
{ yyrellval.ival = 6; return SLPINT; }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 243 "Rellexer.l"
{ yyrellval.ival = 0; return SLPFLT; }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 244 "Rellexer.l"
{ yyrellval.ival = 1; return SLPFLT; }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 245 "Rellexer.l"
{ yyrellval.ival = 2; return SLPFLT; }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 246 "Rellexer.l"
{ yyrellval.ival = 3; return SLPFLT; }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 247 "Rellexer.l"
{ yyrellval.ival = 4; return SLPFLT; }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 248 "Rellexer.l"
{ yyrellval.ival = 5; return SLPFLT; }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 250 "Rellexer.l"
{ return SOLVER; }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 252 "Rellexer.l"
{ return STCVAR; }
	YY_BREAK
case 158:
YY_RULE_SETUP
#line 254 "Rellexer.l"
{ yyrellval.ival = Optvar::attribute;  return STCVARTYP; }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 255 "Rellexer.l"
{ yyrellval.ival = Optvar::coordinate; return STCVARTYP; }
	YY_BREAK
case 160:
YY_RULE_SETUP
#line 256 "Rellexer.l"
{ yyrellval.ival = Optvar::composite;  return STCVARTYP; }
	YY_BREAK
case 161:
YY_RULE_SETUP
#line 257 "Rellexer.l"
{ yyrellval.ival = Optvar::nodalforce; return STCVARTYP; }
	YY_BREAK
case 162:
YY_RULE_SETUP
#line 258 "Rellexer.l"
{ yyrellval.ival = Optvar::fluidparam; return STCVARTYP; }
	YY_BREAK
case 163:
YY_RULE_SETUP
#line 259 "Rellexer.l"
{ yyrellval.ival = Optvar::elecattr;   return STCVARTYP; }
	YY_BREAK
case 164:
YY_RULE_SETUP
#line 260 "Rellexer.l"
{ yyrellval.ival = Optvar::thermattr;  return STCVARTYP; }
	YY_BREAK
case 165:
YY_RULE_SETUP
#line 261 "Rellexer.l"
{ yyrellval.ival = Optvar::mixedvar;	return STCVARTYP; }
	YY_BREAK
case 166:
YY_RULE_SETUP
#line 263 "Rellexer.l"
{ return RGDVELOC; }
	YY_BREAK
case 167:
YY_RULE_SETUP
#line 264 "Rellexer.l"
{ return TRADIATE; }
	YY_BREAK
case 168:
YY_RULE_SETUP
#line 266 "Rellexer.l"
{ return STCANA; }
	YY_BREAK
case 169:
YY_RULE_SETUP
#line 267 "Rellexer.l"
{ return STCDYN; }
	YY_BREAK
case 170:
YY_RULE_SETUP
#line 268 "Rellexer.l"
{ return STCDAM; }
	YY_BREAK
case 171:
YY_RULE_SETUP
#line 269 "Rellexer.l"
{ return STCTRA; }
	YY_BREAK
case 172:
YY_RULE_SETUP
#line 270 "Rellexer.l"
{ return STCELEVAR; }
	YY_BREAK
case 173:
YY_RULE_SETUP
#line 272 "Rellexer.l"
{ return STRESS; }
	YY_BREAK
case 174:
YY_RULE_SETUP
#line 274 "Rellexer.l"
{ return STRVOL; }
	YY_BREAK
case 175:
YY_RULE_SETUP
#line 275 "Rellexer.l"
{ return STRLEVEL; }
	YY_BREAK
case 176:
YY_RULE_SETUP
#line 277 "Rellexer.l"
{ return OPSUM; }
	YY_BREAK
case 177:
YY_RULE_SETUP
#line 279 "Rellexer.l"
{ return S1L; }
	YY_BREAK
case 178:
YY_RULE_SETUP
#line 280 "Rellexer.l"
{ return S1M; }
	YY_BREAK
case 179:
YY_RULE_SETUP
#line 281 "Rellexer.l"
{ return S1U; }
	YY_BREAK
case 180:
YY_RULE_SETUP
#line 283 "Rellexer.l"
{ return S2L; }
	YY_BREAK
case 181:
YY_RULE_SETUP
#line 284 "Rellexer.l"
{ return S2M; }
	YY_BREAK
case 182:
YY_RULE_SETUP
#line 285 "Rellexer.l"
{ return S2U; }
	YY_BREAK
case 183:
YY_RULE_SETUP
#line 287 "Rellexer.l"
{ return SXL; }
	YY_BREAK
case 184:
YY_RULE_SETUP
#line 288 "Rellexer.l"
{ return SXM; }
	YY_BREAK
case 185:
YY_RULE_SETUP
#line 289 "Rellexer.l"
{ return SXU; }
	YY_BREAK
case 186:
YY_RULE_SETUP
#line 291 "Rellexer.l"
{ return SYL; }
	YY_BREAK
case 187:
YY_RULE_SETUP
#line 292 "Rellexer.l"
{ return SYM; }
	YY_BREAK
case 188:
YY_RULE_SETUP
#line 293 "Rellexer.l"
{ return SYU; }
	YY_BREAK
case 189:
YY_RULE_SETUP
#line 295 "Rellexer.l"
{ return SZL; }
	YY_BREAK
case 190:
YY_RULE_SETUP
#line 296 "Rellexer.l"
{ return SZM; }
	YY_BREAK
case 191:
YY_RULE_SETUP
#line 297 "Rellexer.l"
{ return SZU; }
	YY_BREAK
case 192:
YY_RULE_SETUP
#line 300 "Rellexer.l"
{ return CTE; }
	YY_BREAK
case 193:
YY_RULE_SETUP
#line 301 "Rellexer.l"
{ return CTE1; }
	YY_BREAK
case 194:
YY_RULE_SETUP
#line 302 "Rellexer.l"
{ return CTE2; }
	YY_BREAK
case 195:
YY_RULE_SETUP
#line 303 "Rellexer.l"
{ return CONVECT; }
	YY_BREAK
case 196:
YY_RULE_SETUP
#line 305 "Rellexer.l"
{ return TEMP; }
	YY_BREAK
case 197:
YY_RULE_SETUP
#line 306 "Rellexer.l"
{ return THPOWER; }  
	YY_BREAK
case 198:
YY_RULE_SETUP
#line 308 "Rellexer.l"
{ return THICK_rel; }
	YY_BREAK
case 199:
YY_RULE_SETUP
#line 310 "Rellexer.l"
{ return TIME; }
	YY_BREAK
case 200:
YY_RULE_SETUP
#line 312 "Rellexer.l"
{ return FUNVAR; }
	YY_BREAK
case 201:
YY_RULE_SETUP
#line 314 "Rellexer.l"
{ return VELOCITY; }
	YY_BREAK
case 202:
YY_RULE_SETUP
#line 316 "Rellexer.l"
{ return VML; }
	YY_BREAK
case 203:
YY_RULE_SETUP
#line 317 "Rellexer.l"
{ return VMM; }
	YY_BREAK
case 204:
YY_RULE_SETUP
#line 318 "Rellexer.l"
{ return VMU; }
	YY_BREAK
case 205:
YY_RULE_SETUP
#line 320 "Rellexer.l"
{ return VOLTAGE;  }
	YY_BREAK
case 206:
YY_RULE_SETUP
#line 322 "Rellexer.l"
{ return YAWANGLE; }
	YY_BREAK
case 207:
YY_RULE_SETUP
#line 324 "Rellexer.l"
{ return YMODUS; }
	YY_BREAK
case 208:
YY_RULE_SETUP
#line 326 "Rellexer.l"
{ return END; }
	YY_BREAK
case 209:
YY_RULE_SETUP
#line 328 "Rellexer.l"
{ yyrelline_num++; return NewLine; }
	YY_BREAK
case 210:
YY_RULE_SETUP
#line 330 "Rellexer.l"
{ while(yyinput() != '\n') ; yyrelline_num++; }
	YY_BREAK
case 211:
YY_RULE_SETUP
#line 332 "Rellexer.l"
{ return *yyreltext; }
	YY_BREAK
case 212:
YY_RULE_SETUP
#line 334 "Rellexer.l"
/* Just discard spaces */
	YY_BREAK
case 213:
YY_RULE_SETUP
#line 336 "Rellexer.l"
{ yyrellval.ival = atoi(yyreltext) ; return IntConstant ; }
	YY_BREAK
case 214:
#line 339 "Rellexer.l"
case 215:
#line 340 "Rellexer.l"
case 216:
#line 341 "Rellexer.l"
case 217:
#line 342 "Rellexer.l"
case 218:
YY_RULE_SETUP
#line 342 "Rellexer.l"
{
                     yyrellval.fval = atof(yyreltext) ; return DblConstant ; }
	YY_BREAK
case 219:
#line 346 "Rellexer.l"
case 220:
#line 347 "Rellexer.l"
case 221:
YY_RULE_SETUP
#line 347 "Rellexer.l"
{
  int il;
  for(il = 0; yyreltext[il] != 'd' && yyreltext[il] != 'D';) ++il;
  yyreltext[il] = 'e'; yyrellval.fval = atof(yyreltext) ; return DblConstant ; }
	YY_BREAK
case 222:
YY_RULE_SETUP
#line 352 "Rellexer.l"
ECHO;
	YY_BREAK
#line 2145 "Rellexer.C"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 639 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 639 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 638);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 352 "Rellexer.l"

void
yyrelerror(const char  *)
{
 fprintf(stderr,"Syntax Error near line %d : %s\n", yyrelline_num,yyreltext);
}

int yyrelwrap()
{
 return 0;
}

#endif
