#!/bin/sh

# Convert Encapsulated PostScript to PDF, retaining the Bounding Box.
# Just like the standard ps2pdf, but with one extra Ghostscript option.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
version=14

ps2pdf="`dirname $0`/ps2pdf$version"
if test ! -x "$ps2pdf"; then
 ps2pdf="ps2pdf$version"
fi
exec "$ps2pdf" -dEPSCrop "$@"

